security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    service-url:
#      defaultZone: http://user:password123@localhost:8761/eureka
#      defaultZone: http://user:password123@121.5.179.95:8761/eureka
      defaultZone: http://user:password123@123.249.43.78:8761/eureka
logging:
  level:
    root: INFO
